choco install -y  hwinfo
choco install -y  gpu-z
choco install -y  hwmonitor
choco install -y  heavyload
choco install -y  ultrasearch
choco install -y  sysinternals
choco install -y  winscp.install
choco install -y  paint.net
choco install -y  adobereader
choco install -y  jre8
choco install -y  7zip.install
choco install -y  vlc
choco install -y  foxitreader
choco install -y  gimp
choco install -y  curl
choco install -y  wget
choco install -y  virtualbox
choco install -y  golang
choco install -y  irfanview
choco install -y  audacity
choco install -y  tortoisesvn
choco install -y  evernote
choco install -y  rufus
choco install -y  rapidee
choco install -y  nodejs.install
choco install -y  cmake.install
choco install -y  inkscape
choco install -y  putty.install
choco install -y  freecad
choco install -y notepadplusplus
choco install -y conemu
choco install -y firacode cascadiacode