# base defaults are in https://github.com/Azure/azure-storage-fuse/blob/main/setup/baseConfig.yaml

azstorage:
  # to get below info, goto storage account in Azure Portal, click on Containers menu, click on specific container, click on Properties menu, look at URL
  endpoint: YOUR_ACCOUNT_NAME.blob.core.windows.net
  account-name: YOUR_ACCOUNT_NAME
  account-key: YOUR_ACCOUNT_KEY
  container: YOUR_CONTAINER_NAME
  # don't change below
  type: block
  mode: key

allow-other: true # allow other users to access the mounted directory
# read-only: true # mount in read only mode - used for Streaming and FUSE
nonempty: true # allow mounting on non-empty directory - used for FUSE

file_cache:
  path: /tmp/blobfuse
