# from https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags
FROM nvcr.io/nvidia/pytorch:22.12-py3

# Labels for the docker
LABEL description="Docker for AI Research and Development" \
      repository="sytelus" \
      tag="latest" \
      creator="Shital Shah" \
      tooltype="pytorch" \
      tooltypeversion="1.0.0" \
      createtime="01/30/2023"
